const Icons = {
    iconfont: 'mdi',
    values: {
        monitorDashboard: 'mdi-monitor-dashboard',
        monitorArrowDown: 'mdi-monitor-arrow-down-variant',
        formatRotate90: 'mdi-format-rotate-90',
        crosshairsGps: 'mdi-crosshairs-gps',
        cogTransfer: 'mdi-cog-transfer-outline',
        account: 'mdi-account-outline',
        arrowRightBox: 'mdi-arrow-right-bold-box-outline',
        arrowLeftBox: 'mdi-arrow-left-bold-box-outline',
        checkBoxMarkedCircle: 'mdi-checkbox-marked-circle',
        delete: 'mdi-delete',
        airplane: 'mdi-airplane',
        arrowLeftRight: 'mdi-arrow-left-right',
        arrowUpDown: 'mdi-arrow-up-down',
        formatAlignLeft: 'mdi-format-align-left',
        formatAlignCenter: 'mdi-format-align-center',
        formatAlignRight: 'mdi-format-align-right',
        send: 'mdi-send',
        heartCircle: 'mdi-heart-circle',
        briefcase: 'mdi-briefcase-outline',
        video: 'mdi-video-outline',
        layersOff: 'mdi-layers-off',
        textBoxCheck: 'mdi-text-box-check-outline',
        mapMarkerPath: 'mdi-map-marker-path',
        quadcopter: 'mdi-quadcopter',
        speedometer: 'mdi-speedometer',
        download: 'mdi-download',
        home: 'mdi-home',
        arrowDownLeftBold: 'mdi-arrow-down-left-bold',
        closeOctagonOutline: 'mdi-close-octagon-outline',
        radioboxBlank: 'mdi-radiobox-blank',
        rotateOrbit: 'mdi-rotate-orbit',
        altimeter: 'mdi-altimeter',
        googleCirclesGroup: 'mdi-google-circles-group',
        logoutVariant: 'mdi-logout-variant',
        mapMarkerDistance: 'mdi-map-marker-distance',
        close: 'mdi-close',
        cardBulletedSettingsOutline: 'mdi-card-bulleted-settings-outline',
        pencil: 'mdi-pencil',
        plus: 'mdi-plus',
        ticketConfirmationOutline: 'mdi-ticket-confirmation-outline',
        timerOffOutline: 'mdi-timer-off-outline',
        batteryOffOutline: 'mdi-battery-off-outline',
        batteryMedium: 'mdi-battery-medium',
        batteryLow: 'mdi-battery-low',
        batteryHigh: 'mdi-battery-high',
        latitude: 'mdi-latitude',
        longitude: 'mdi-longitude',
        networkStrength4: 'mdi-network-strength-4',
        networkStrength3: 'mdi-network-strength-3',
        networkStrength2: 'mdi-network-strength-2',
        networkStrength1: 'mdi-network-strength-1',
        networkStrengthOffOutline: 'mdi-network-strength-off-outline',
        magnifyMinusOutline: 'mdi-magnify-minus-outline',
        magnifyPlusOutline: 'mdi-magnify-plus-outline',
        satelliteVariant: 'mdi-satellite-variant',
        accessPoint: 'mdi-access-point',
        selectAll: 'mdi-select-all'
    }
}

export default Icons
export { Icons }
